fixtures:
  repositories:
    stdlib:  git://github.com/puppetlabs/puppetlabs-stdlib.git
    registry: git://github.com/puppetlabs/puppetlabs-registry.git
  symlinks:
    windows_eventlog: "#{source_dir}"
